name: Release config & scanners

on:
  push:
    tags:
      - "*"
  
jobs:
  release:
    name: "Release configuration & scanners"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Generate configuration
        run: poetry run python -m scripts.main generate-config > config.json

      - name: Download scanners
        run: poetry run python -m scripts.main download-scanners
        
      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Upload assets
        run: |
          gh release upload --clobber ${{ github.ref_name }} config.json output/scanners/*
        env:
          GITHUB_TOKEN: ${{ github.token }}
