name: Release config & scanners

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
        required: true
        type: string
  
jobs:
  release:
    name: "Release configuration & scanners"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Generate configuration
        run: poetry run python -m scripts.main generate-config > config.json

      - name: Download scanners
        run: poetry run python -m scripts.main download-scanners

      - uses: AButler/upload-release-assets@v3.0
        with:
          files: "config.json;output/scanners/*"
          repo-token: ${{ github.token }}
          release-tag: ${{ inputs.version }}
