name: Release config & scanners

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Release configuration & scanners'
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t policies-config .

      - name: Run release script
        run: docker run --rm -e GITHUB_TOKEN=${{ github.token }} -e GITHUB_TAG=${{ github.ref_name }} policies-config bash -c "make release"
