name: Release config & scanners

on:
  push:
    tags:
      - "*"
  
jobs:
  release:
    name: "Release configuration & scanners"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Generate configuration
        run: poetry run python -m scripts.main generate-config > config.json

      - name: Download scanners
        run: poetry run python -m scripts.main download-scanners

      - name: Create static data
        run: |
          git clone https://github.com/aquasecurity/trivy-checks.git
          poetry run python -m scripts.main generate-static-data trivy-checks/avd_docs
          zip -j iac_rules_remediations.zip output/static-data/*
        
      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Upload assets
        run: |
          gh release upload --clobber ${{ github.ref_name }} config.json output/scanners/* iac_rules_remediations.zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
